# Generated by Django 5.0.3 on 2025-03-23 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('expense', 'Expense')], max_length=10)),
                ('category', models.CharField(choices=[('essential', 'Essential Expenses'), ('fixed', 'Fixed Expenses'), ('pharmacy', 'Pharmacy'), ('transport', 'Transport'), ('maintenance', 'Maintenance'), ('market', 'Market'), ('education', 'Education'), ('entertainment', 'Entertainment')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
